apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-nodejs-app
  labels:
    app: simple-nodejs-app
spec:
  replicas: 3  # Number of pod replicas
  selector:
    matchLabels:
      app: simple-nodejs-app
  template:
    metadata:
      labels:
        app: simple-nodejs-app
    spec:
      containers:
        - name: simple-nodejs-app
          image: simple-nodejs-app:latest  # Replace with your Docker image name and version
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
