apiVersion: v1
kind: Service
metadata:
  name: simple-nodejs-service
spec:
  selector:
    app: simple-nodejs-app
  type: NodePort
  ports:
    - port: 3000        # Port within the cluster
      targetPort: 3000  # Port where the application is running inside the container
      nodePort: 32000   # External port on each node (choose a port between 30000 and 32767)
